---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: unleash-db-volume
  labels:
    type: local
    app: unleash
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unleash-db-claim
  labels:
    app: unleash
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unleash-db-config
  labels:
    app: unleash-db
data:
  POSTGRES_DB: db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: somepassword
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-db
  labels:
    app: unleash-db
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: unleash-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unleash-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unleash-db
    spec:
      volumes:
        - name: unleash-db-storage
          persistentVolumeClaim:
            claimName: unleash-db-claim
      containers:
        - name: unleash
          image: postgres:10.4
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          env:
          - name: PGDATA 
            value: /tmp
          envFrom:
            - configMapRef:
                name: unleash-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: unleash-db-storage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unleash-server
  labels:
    app: unleash-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unleash-server
    spec:
      containers:
      - name: unleash-server
        #image: unleashorg/unleash-server:3.2.14
        image: jetzlstorfer/unleash-server-basicauth:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4242
        env:
        - name: NODE_ENV
          value: 'production'
        - name: DATABASE_URL
          value: postgres://postgres:somepassword@unleash-db.unleash.svc.cluster.local/db
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-server-service
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http-port":"HTTP"}'
  labels:
    app: unleash-server
spec:
  type: NodePort
  selector:
    app: unleash-server
  ports:
  - name: http-port
    port: 80
    targetPort: 4242
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: unleash-server-ingress
  labels:
    app: unleash-server
  annotations:
    kubernetes.io/ingress.global-static-ip-name: unleash-server-ip
spec:
  tls:
    - secretName: ssl-secret
  backend:
    serviceName: unleash-server-service
    servicePort: 80
